clear;
emuee_nh = load('Data/emuee_nh.mat');
emuee_ih = load('Data/emuee_ih.mat');
dune_nh = load('Data/DUNE_nh.mat');
dune_ih = load('Data/DUNE_ih.mat');
exp_nh = load('Data/Exp_NH.mat');
exp_ih = load('Data/Exp_IH.mat');
nonunit_nh = load('Data/Nonunit_nh.mat');
nonunit_ih = load('Data/Nonunit_ih.mat');
m = 0.0:0.002:0.20; % Lightest neutrino mass range
emuee_nh = emuee_nh.emu_ee;
emuee_ih = emuee_ih.emu_ee;
dune_nh = dune_nh.minValuesDune;
dune_ih = dune_ih.minValuesDune;
exp_nh = exp_nh.minValuesExp;
exp_ih = exp_ih.minValuesExp;
nonunit_nh = nonunit_nh.minValuesNonunit;
nonunit_ih = nonunit_ih.minValuesNonunit;
cflv_nhplot = plot(m,emuee_nh,'-b');
hold on;
cflv_ihplot = plot(m,emuee_ih,'--b');
dune_nhplot = plot(m,dune_nh,'-k');
dune_ihplot = plot(m,dune_ih,'--k');
%exp_nhplot = plot(m,exp_nh,'-r');
%exp_ihplot = plot(m,exp_ih,'--r');
nonunit_nhplot = plot(m,nonunit_nh,'-m');
nonunit_ihplot = plot(m,nonunit_ih,'--m');
plottables = [cflv_nhplot cflv_ihplot dune_nhplot nonunit_nhplot nonunit_ihplot];
Beautify(false,9,12,20);
legend(plottables,{'{\fontsize{15}CFLV (NH)}','{\fontsize{15}CFLV (IH)}','{\fontsize{15}DUNE (NH/IH)}','{\fontsize{15}Nonunitarity (NH)}','{\fontsize{15}Nonunitarity (IH)}'},'Location','NorthEastOutside');